"""initial schema

Revision ID: 58ea04b7bc37
Revises: 
Create Date: 2026-05-06 09:50:13.950619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '58ea04b7bc37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'cleaning', 'merging', 'analyzing', 'saving', 'evaluating', 'done', 'failed', name='jobstatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('rows_input', sa.Integer(), nullable=True),
    sa.Column('rows_output', sa.Integer(), nullable=True),
    sa.Column('rows_failed', sa.Integer(), nullable=True),
    sa.Column('cleaning_report', sa.JSON(), nullable=True),
    sa.Column('raw_keys', sa.JSON(), nullable=True),
    sa.Column('cleaned_dataset_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    # 註: pipeline_job.recommendation_id → recommendation.id 的 FK 在所有表建好後才加
    # 因為 pipeline_job <-> recommendation 互相 reference,有循環依賴
    )
    op.create_index(op.f('ix_pipeline_job_created_at'), 'pipeline_job', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_job_customer_id'), 'pipeline_job', ['customer_id'], unique=False)
    op.create_index(op.f('ix_pipeline_job_status'), 'pipeline_job', ['status'], unique=False)
    op.create_table('prompt_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_variant_created_at'), 'prompt_variant', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompt_variant_is_active'), 'prompt_variant', ['is_active'], unique=False)
    op.create_index(op.f('ix_prompt_variant_name'), 'prompt_variant', ['name'], unique=False)
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_segment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_variant_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('pipeline_job_id', sa.Integer(), nullable=True),
    sa.Column('hubspot_sync_status', sa.Enum('pending', 'syncing', 'synced', 'failed', name='hubspotsyncstatus'), nullable=False),
    sa.Column('hubspot_contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hubspot_note_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hubspot_synced_at', sa.DateTime(), nullable=True),
    sa.Column('hubspot_sync_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hubspot_sync_retries', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_job_id'], ['pipeline_job.id'], ),
    sa.ForeignKeyConstraint(['prompt_variant_id'], ['prompt_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_confidence_score'), 'recommendation', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_recommendation_customer_id'), 'recommendation', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recommendation_customer_segment'), 'recommendation', ['customer_segment'], unique=False)
    op.create_index(op.f('ix_recommendation_generated_at'), 'recommendation', ['generated_at'], unique=False)
    op.create_index(op.f('ix_recommendation_hubspot_contact_id'), 'recommendation', ['hubspot_contact_id'], unique=False)
    op.create_index(op.f('ix_recommendation_hubspot_sync_status'), 'recommendation', ['hubspot_sync_status'], unique=False)
    op.create_index(op.f('ix_recommendation_prompt_variant_id'), 'recommendation', ['prompt_variant_id'], unique=False)
    op.create_index(op.f('ix_recommendation_schema_version'), 'recommendation', ['schema_version'], unique=False)
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('judge_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('specificity_score', sa.Float(), nullable=False),
    sa.Column('actionability_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('judge_reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('judge_input_tokens', sa.Integer(), nullable=True),
    sa.Column('judge_output_tokens', sa.Integer(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_evaluated_at'), 'evaluation', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_evaluation_overall_score'), 'evaluation', ['overall_score'], unique=False)
    op.create_index(op.f('ix_evaluation_recommendation_id'), 'evaluation', ['recommendation_id'], unique=False)

    # === 補上循環 FK: pipeline_job.recommendation_id → recommendation.id ===
    op.create_foreign_key(
        'fk_pipeline_job_recommendation_id',
        'pipeline_job', 'recommendation',
        ['recommendation_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pipeline_job_recommendation_id', 'pipeline_job', type_='foreignkey')
    op.drop_index(op.f('ix_evaluation_recommendation_id'), table_name='evaluation')
    op.drop_index(op.f('ix_evaluation_overall_score'), table_name='evaluation')
    op.drop_index(op.f('ix_evaluation_evaluated_at'), table_name='evaluation')
    op.drop_table('evaluation')
    op.drop_index(op.f('ix_recommendation_schema_version'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_prompt_variant_id'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_hubspot_sync_status'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_hubspot_contact_id'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_generated_at'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_customer_segment'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_customer_id'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_confidence_score'), table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_index(op.f('ix_prompt_variant_name'), table_name='prompt_variant')
    op.drop_index(op.f('ix_prompt_variant_is_active'), table_name='prompt_variant')
    op.drop_index(op.f('ix_prompt_variant_created_at'), table_name='prompt_variant')
    op.drop_table('prompt_variant')
    op.drop_index(op.f('ix_pipeline_job_status'), table_name='pipeline_job')
    op.drop_index(op.f('ix_pipeline_job_customer_id'), table_name='pipeline_job')
    op.drop_index(op.f('ix_pipeline_job_created_at'), table_name='pipeline_job')
    op.drop_table('pipeline_job')
    # ### end Alembic commands ###
